version: "3.7"
services:
  dr-ver:
    build: .
    container_name: dr-ver
    restart: unless-stopped
    command:
      - "--bind=0.0.0.0:8080"
      - "--access-logfile=-"
    environment:
      - "REDIS_HOST=redis"
    depends_on: 
      - redis
    ports:
      - "80:8080"
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis
        target: /data
volumes:
  redis:
